title: NLP-Based Grant Analysis
description: Exploratory Analysis of NSF Standard Grants Using NLP and Data Visualization Tools
show_downloads: false
google_analytics:
remote_theme: pages-themes/midnight@v0.2.0
#theme: midnight
plugins: 
- jekyll-remote-theme

